package.json, scripts/cli/base.cli.ts, scripts/types.ts, scripts/utils.ts, terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/helm/variables.tf, terraform/workspaces/paragon/variables.tf, yarn.lock
- PARA-7131
conditionally run microservices based on version
Migrations are failing on initial install for enterprise installations. This is due to migrations that references tables in external databases that haven't been created yet. A quick fix is to install an earlier version, have the migrations run, then upgrade the latest version. However that causes helm install failures because some microservices in the helm chart haven't been released yet.
This PR primarily aims to allow conditional installation of charts for microservices based on the semver version it was introduced.
- added `compare-versions` package + use to compare app version with versions when microservices were introduced to determine whether or not to install sub chart
- created helper function to determine whether or …
=> Conditionally run microservices

terraform/workspaces/infra/templates/bastion/bastion-startup.tpl.sh
The original location recently started returning the GPG key in ascii instead of the binary format.
See: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1557062278
=> fix(infra): replace apt-key location from cloud.google to k8s.io

README.md, terraform/workspaces/infra/cluster/cluster.tf, terraform/workspaces/infra/cluster/variables.tf, terraform/workspaces/infra/modules.tf, terraform/workspaces/infra/variables.tf, terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/helm/variables.tf, terraform/workspaces/paragon/modules.tf, terraform/workspaces/paragon/variables.tf
This PR adds the ability to configure the kubernetes version and enabling the [AWS EBS CSI Driver addon](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) which is needed for Kubernetes versions >= 1.23.
EKS ends support for Kubernetes version 1.22 on Sunday, June 4, 2023, which is why we're upgrading the default Kubernetes version.
Existing installations will have to manually add the EBS CSI Driver to prevent zero downtime, but that would break deployments to the `infra` workspace on subsequent deployments because it already exists. Allowing disabling creation of it adds backwards compatibility. 
- allow configuring kubernetes version
- change default kubernetes version from `1.22` -> `1.25`
=> Configurable K8 Version + EBS CSI Driver

.dockerignore, README.md, terraform/workspaces/infra/modules.tf, terraform/workspaces/infra/postgres/rds.tf, terraform/workspaces/infra/postgres/variables.tf, terraform/workspaces/infra/variables.tf
- PARA-8070
This PR provides options for working with snapshots. When doing load testing or working with other ephemeral environments, we don't always want to create our data from scratch. With these changes, we can take down environments (to save costs) and restore them later from snapshots (to save time).
- added `RDS_FINAL_SNAPSHOT_ENABLED` boolean option to `infra` workspace
- added `RDS_RESTORE_FROM_SNAPSHOT` boolean option to `infra` workspace
- added datasources to fetch existing snapshots when `RDS_RESTORE_FROM_SNAPSHOT` enabled
- updated README with instructions for options
- added `.dockerignore` file (reduced `make build` command execution time from over a minute to about 1 second)
=> Feature/para 8070/rds restore from snapshot

README.md, terraform/templates/main.tpl.tf, terraform/workspaces/infra/postgres/outputs.tf, terraform/workspaces/infra/postgres/rds.tf, terraform/workspaces/infra/postgres/variables.tf, terraform/workspaces/paragon/.terraform.lock.hcl, terraform/workspaces/paragon/alb/dns.tf, terraform/workspaces/paragon/alb/providers.tf, terraform/workspaces/paragon/alb/variables.tf, terraform/workspaces/paragon/modules.tf, terraform/workspaces/paragon/providers.tf, terraform/workspaces/paragon/variables.tf
- PARA-8070
This PR is a follow-on to https://github.com/useparagon/aws-on-prem/pull/16. I found a few issues over the weekend where databases restored from snapshots had issues saving or being restored from snapshots.
1. On subsequent Terraform runs, databases created from snapshots were destroyed and recreated because the `aws_db_snapshot` datasource updated with a more recent automated snapshot.
2. Databases restored from snapshots were destroyed and recreated because the `random_string` resources for creating the postgres usernames and password would change. The [Terraform docs](https://registry.terraform.io/providers/-/aws/4.52.0/docs/resources/db_instance) for the `aws_db_instance` resource show specify that `username` and `password` are optional when restoring from a snapshot.
3. …
=> Fix RDS restore from snapshot

terraform/workspaces/infra/postgres/rds.tf, terraform/workspaces/infra/postgres/variables.tf, terraform/workspaces/infra/s3/s3-app.tf
This PR has some cost savings + RDS performance changes.
**RDS**
This changes the `hermes` database from `gp2` to `gp3` config with 3000 provisioned IOPs. This is better for high volume installations because `hermes` usually has consistent traffic as opposed to burstable.
**S3**
This PR applies the expiration policy to non-current versions for the system bucket.
=> Hermes RDS Config + S3 Expiration

terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/variables.tf
This PR generates the public urls for the workers to be used as environment variables within the microservices. This is needed for recent changes that went in in which requests are made to `worker-proxy` via the public internet.
Additionally this PR increases the replica count for the application load balancer pods from the default `2` to `5`.
=> generate env vars for worker variables

terraform/workspaces/infra/cluster/cluster.tf, terraform/workspaces/infra/cluster/security.tf
Replaces exclusive `aws_iam_policy_attachment` usage with `aws_iam_role_policy_attachment`.
The aws_iam_policy_attachment resource creates exclusive attachments of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single aws_iam_policy_attachment resource. This means that even any users/roles/groups that have the attached policy via any other mechanism (including other Terraform resources) will have that attached policy revoked by this resource. Using aws_iam_role_policy_attachment allows Paragon roles to attach policies without affecting other roles.
- replace `aws_iam_policy_attachment` with `aws_iam_role_policy_attachment`
- perform a Terraform apply and ensure that other roles that have any of the …
=> fix(infra): removed aws_iam_policy_attachment usage

terraform/workspaces/infra/.terraform.lock.hcl, terraform/workspaces/infra/postgres/variables.tf, terraform/workspaces/paragon/variables.tf
This PR removes `beethoven-exporter` from the monitors, which was removed in v2.88.2.
- remove `beethoven-exporter` from monitors
- fix postgres IOPS config for small RDS instances
- updated Terraform dependencies
=> Remove beethoven exporter

terraform/workspaces/paragon/.terraform.lock.hcl, terraform/workspaces/paragon/alb/providers.tf
Removes `version = "~> 3.0"` specification in the `alb` module since it conflicts with the `version = "~> 4.0"` requirement in `./main.tf`. The `alb` module will just inherit the version that is defined in the root now.
- remove `version` provider declaration in submodule
Error being addressed:
=> fix(infra): removed conflicting provider version

terraform/workspaces/infra/bastion/tunnel.tf, terraform/workspaces/infra/bastion/variables.tf, terraform/workspaces/infra/modules.tf, terraform/workspaces/infra/variables.tf
- PARA-9734
Adds explicit Cloudflare Tunnel subdomain variable to avoid potential conflicts.
The subdomain of the Cloudflare Zero Trust tunnel was being derived from the `app_name` or `organization`. This could lead to conflicts across customer environments if those weren't set. This also allows setting/changing the tunnel domain without having to recreate countless other resources that share the same name variables.
- added new `cloudflare_tunnel_subdomain` variable for setting tunnel domain
none
- consolidate `on-prem` and `aws-on-prem` so this work doesn't have to be duplicated across repos
- deploy with tunnel settings all set and ensure that domain in Cloudflare matches values
- deploy with tunnel enabled but without setting `cloudflare_tunnel_subdomain` and ensure that Terraform …
=> fix(infra): add explicit tunnel subdomain variable

package.json, scripts/cli/base.cli.ts
- PARA-9489
remove plato in versions >= 2.94.3
The `plato` microservice was removed in v2.94.3. https://useparagon.atlassian.net/browse/PARA-9479
This PR updates the installer script to not include `plato` for versions equal or after that.
=> remove plato in versions >= 2.94.3

terraform/workspaces/infra/variables.tf, terraform/workspaces/paragon/.terraform.lock.hcl, terraform/workspaces/paragon/modules.tf, terraform/workspaces/paragon/uptime/monitors.tf, terraform/workspaces/paragon/uptime/outputs.tf, terraform/workspaces/paragon/uptime/provider.tf, terraform/workspaces/paragon/uptime/variables.tf, terraform/workspaces/paragon/uptime/webhook.tf, terraform/workspaces/paragon/variables.tf
- PARA-8155
Automates BetterUptime monitor and webhook creation.
Creates BetterUptime monitors for each microservice. Also creates an incoming Grafana webhook and sets the `MONITOR_GRAFANA_UPTIME_WEBHOOK_URL` environment variable with it. Same changes were made in https://github.com/useparagon/on-prem/pull/139.
Changed default EKS version from `1.25` to `1.28` to align with all current deplyments.
- created BetterUptime monitors and webhook
- configured Grafana to use the webhook
- EKS version bump
- verify that BetterUptime monitors are created in a group for each microservice
- verify that BetterUptime incoming Grafana webhook is created
- verify that `MONITOR_GRAFANA_UPTIME_WEBHOOK_URL` is set to webhook URL on Grafana task
none
An API token will have to be created for each deployment …
=> feat(monitor): added betterstack uptime checks

terraform/workspaces/infra/outputs.tf, terraform/workspaces/infra/s3/s3-app.tf, terraform/workspaces/paragon/monitors/grafana.tf, terraform/workspaces/paragon/monitors/pgadmin.tf
This PR fixes the outputs in the infra workspace when restoring the RDS database from a snapshot (`RDS_RESTORE_FROM_SNAPSHOT=true`). Null values aren't allowed in string interpolations.
This use case is primarily used when spinning up + down ephemeral environments when load testing.
- disable bucket versioning when `DISABLE_DELETION_PROTECTION=true`, which makes it harder + take longer to delete buckets
- only allow lowercase characters when generating Grafana and PGAdmin emails
=> fix infra outputs when restoring from snapshots

terraform/workspaces/infra/postgres/rds.tf
Upgrades RDS CA certificate to a newer version.
Prior to January 26, 2024 the default RDS CA certificate was `rds-ca-2019`. This is set to expire on August 22, 2024. So any databases using the default `ca_cert_identifier` will have to be upgraded by setting the value explicitly to the new default value `rds-ca-rsa2048-g1`. 
- explicitly set RDS `ca_cert_identifier` to `rds-ca-rsa2048-g1`
- enabled auto minor upgrades for security and consistency across environments
- Verify that certificate details reflect those in screenshots.
Versions of Postgres prior to 12.11 will require a restart which means 1-2 minutes of downtime.
=> chore(infra): upgrade RDS cert and minor version

terraform/workspaces/infra/s3/s3-app.tf
S3 policy for minio was missing permissions related to multipart operations. This was preventing large objects from being uploaded.
Added the following to address this:
- `s3:ListBucketMultipartUploads`
- `s3:ListMultipartUploadParts`
- `s3:AbortMultipartUpload`
Also added `s3:DeleteObjectVersion` for consistency with cloud environments and removed duplicate `s3:GetObjectRetention`.
=> fix(infra): missing multipart perms

Makefile, package.json, scripts/cli/base.cli.ts, terraform/workspaces/paragon/outputs.tf, terraform/workspaces/paragon/uptime/outputs.tf
- PARA-10430
Added `prepare-infra` and `prepare-paragon` CLI commands that will create and populate the relevant `vars.auto.tfvars` files. This will allow Terraform to be run locally without Docker when necessary. Unlike the deploy commands, these commands don't touch the Terraform token file, main.tf or attempt any other Terraform operations.
Also added some output variables for the uptime module to help debug when Better Uptime monitors are not created.
=> terraform prep without docker

terraform/workspaces/infra/cloudtrail/s3.tf, terraform/workspaces/infra/network/logs.tf, terraform/workspaces/infra/network/network.tf, terraform/workspaces/infra/network/security.tf, terraform/workspaces/infra/s3/s3-logs.tf, terraform/workspaces/paragon/.terraform.lock.hcl, terraform/workspaces/paragon/uptime/monitors.tf
- PARA-9761
Switched VPC flow logs from CloudWatch to S3.
Switching the VPC flow logs from CloudWatch to S3 can provide significant cost savings for this infrequently accessed data. An S3 VPC endpoint is also created so these logs bypass the NAT Gateway for additional security and cost savings. The other logging S3 buckets also had their lifecycle configs updated to match the VPC flow logs bucket for more consistent data retention rules and cost savings.
One unrelated change was made to pause the uptime checks by default to avoid alarms in newly provisioned environments.
- switched flow logs to S3
- added S3 VPC endpoint
- added lifecycle configs for other log buckets
- paused uptime checks by default
=> feat(monitor): switch vpc flow logs from cloudwatch to s3

package.json, terraform/workspaces/infra/redis/variables.tf
- PARA-11366
Added additional AWS Elasticache family types that support autoscaling. See [Auto Scaling ElastiCache (Redis OSS) clusters](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/AutoScaling.html) for more details.
=> chore(infra): added additional redis types that support autoscaling

terraform/workspaces/infra/cluster/cluster.tf, terraform/workspaces/infra/variables.tf
- PARA-11579
Updates Terraform to support EKS Kubernetes engine 1.31.
No chart changes were required. None are expected for 1.32 support either. The EBS CSI had issues with the latest version. `v1.32.0-eksbuild.1` is compatible with EKS 1.28 - 1.32. This update buys us until November 26, 2025 before another update is needed.
- updated EBS CSI add-on version
- updated default `k8_version`
None
All on-prem AWS environments will need this change in the next 6 weeks before 1.28 enters extended support.
Deploy changes and ensure nodes are upgraded and replaced without downtime.
None
The k8s upgrades have to happen one at a time (1.28 -> 1.29 -> 1.30 -> 1.31).
=> chore(infra): update EKS version to 1.31

terraform/workspaces/infra/bastion/ec2.tf, terraform/workspaces/infra/cluster/kms.tf, terraform/workspaces/infra/cluster/variables.tf, terraform/workspaces/infra/modules.tf, terraform/workspaces/infra/resource-group.tf, terraform/workspaces/infra/variables.tf, terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/helm/storage.tf
- PARA-11834
- PARA-12103
Encrypts bastion EBS volumes. Allows better control of KMS admins. Removes unused resource group.
Switches to using a forked version of the bastion module to provide more fine-grained control over the volume encryption settings.
Allows setting KMS key administrators instead of just defaulting to only the current executing user.
Removes unused resource group to further limit required IAM permissions.
- new bastion module
- kms key admin variables
- removed resource group
=> fix(infra): EBS and KMS security improvements

scripts/cli/base.cli.ts, scripts/constants.ts, terraform/workspaces/infra/bastion/ec2.tf, terraform/workspaces/paragon/alb/dns.tf, terraform/workspaces/paragon/alb/variables.tf, terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/helm/variables.tf, terraform/workspaces/paragon/modules.tf, terraform/workspaces/paragon/variables.tf
- PARA-12897
Adds `flipt` feature flag support.
Adds `flipt` as a supported microservice in the setup scripts. Adds optional parameter support and defaults. Sets relevant environment variables. Introduces `public_microservices` support so `flipt` endpoint is not exposed publicly.
- added flipt support
- added bastion log cleanup for SOC2
none
- Deploy updated charts and configs
- Verify that flipt pod starts and remains stable
- Verify that other pods reference flipt with `FEATURE_FLAG_PLATFORM_ENDPOINT: http://flipt:1722`
- Verify that flipt UI is accessible and pulling a flag from the repo
none
- some deployments had flipt installed manually and would need cleanup
=> feat(infra): added flipt microservice

README.md, package.json, scripts/cli/base.cli.ts, terraform/workspaces/infra/bastion/variables.tf, terraform/workspaces/infra/network/logs.tf, terraform/workspaces/paragon/alb/dns.tf, terraform/workspaces/paragon/helm/helm.tf, terraform/workspaces/paragon/helm/variables.tf, terraform/workspaces/paragon/modules.tf, terraform/workspaces/paragon/variables.tf
- PARA-13377
Adds support for local feature flag yaml files.
Air-gapped or unmanaged deployments may not want to pull feature flags from a git repository. Since many new Paragon features are behind feature flags local support is required. This adds the ability to have a `.secure/features.yml` defined locally that will populate a ConfigMap that is mounted to the Flipt pod.
- updated TS to populate Terraform variable with base64 string of features.yml
- configured local storage settings vs git repo based on provided features
- creates configMap and volume mounts for features if provided
- cleaned up some old TODOs
- PARA-13400 implement similar solution in enterprise repo
- deploy to AWS with a `.secure/features.yml`
- ensure Flipt pod uses local storage and mounts ConfigMap
- ensure Flipt …
=> added local flipt feature flag support

.gitignore, package.json, terraform/workspaces/infra/postgres/rds.tf
- PARA-13445
Adds postgres16 RDS parameter group to prepare for upgrade.
A new database parameter group must be created for postgres 16 to allow the database to be upgraded from 12 to 16 with minimal changes in the AWS Console.
- added `postgres16` parameter group
none
New Helm charts will be needed to ensure zero data loss during the upgrade.
Deploy and verify that there are two DB parameter groups. One for the selected `postgres_family` and one for `postgres16`.
none
none
=> rds: added postgres16 param group

package.json, scripts/cli/base.cli.ts, scripts/constants.ts, terraform/workspaces/paragon/variables.tf
- [PARA-13456](https://useparagon.atlassian.net/browse/PARA-13456)
Added cache-replay service to aws-on-prem repo
Added support for cache-replay service as supported microservice with default varaibles.
- Added config values to Terraform
[PARA-13456]: https://useparagon.atlassian.net/browse/PARA-13456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> infra: added cache-replay service

package.json, terraform/workspaces/paragon/variables.tf
- PARA-13612
Enabled feature flags by default.
Set `FEATURE_FLAG_PLATFORM_ENABLED = true` by default. Added new `WORKER_WORKFLOWS` default values. Removed some legacy variable defaults.
- terraform changes
- set email notifier default to "none"
none
- verify that charts deploy cleanly
=> fix: enabled feature flags by default

.github/CODEOWNERS
- PARA-15263
Add `CODEOWNERS`  to the repository
This pr adds `infrastructure` team as code owner for this repository
=> added code owner to repo
